#!/bin/bash
source /etc/profile

# Source Environment for SSH Agent
. /home/budsell/.ssh/agent

BODY=`/usr/bin/ssh admin@129.39.22.86 "netstat -na | grep 52.100.254.25"`
CLOSED_STATUS=`echo $BODY | grep CLOSE_WAIT | wc -l`
ESTABLISHED_STATUS=`/usr/bin/ssh admin@129.39.22.86 "netstat -na | grep 52.100.254.25|grep -c ESTABLISHED"`

if ([[ $ESTABLISHED_STATUS -lt 2 ]] && [[ $CLOSED_STATUS -ne 0 ]]); then
echo -e "$BODY \n\n Please create new ticket and investigate immediately. PDP Daemon may need restarted" | mail -s "CRITICAL Dupont - Southbury FW2 process failure `date --utc '+%m-%d-%Y %R GMT'`" budsell@us.ibm.com
else
echo -e "$BODY" | mail -s "OK Dupont - Southbury FW2 `date --utc '+%m-%d-%Y %R GMT'`" budsell@us.ibm.com
fi
